# Уровень 0
## Задание 1
- Создайте матрицу 3 на 3, заполненную числами от 1 до 9
- Прибавьте к ней матрицу с единицами на диагонале
- Умножьте полученную матрицу на вектор (1, 2, 3)
- Вычислить транспонированную матрицу A^T от полученной в результате прибавления матрицы
- Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
import numpy as np

In [ ]:
A1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
A2 = np.eye(3)
A3 = A1 + A2
print(A3)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [ ]:
vector = np.array([1, 2, 3])
res = np.dot(vector, A3)
print(res)

[31. 38. 45.]


In [ ]:
np.transpose(A3) # транспонированная матрица

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
A4 = np.linalg.inv(A3) # обратная матрица
print(A3@A4)

[[ 1.00000000e+00 -3.33066907e-16  6.66133815e-16]
 [-5.32907052e-15  1.00000000e+00  1.33226763e-15]
 [-1.77635684e-15 -1.11022302e-15  1.00000000e+00]]


# Уровень 1
## Задание 2
Найдите собственные значения и собственные вектора матрицы:

In [ ]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
np.linalg.eig(m) # собственные значения и собственные вектора

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [ ]:
res2 = np.linalg.eig(m)
res3 = res2[1]
res4 = np.transpose(res3) # транспоннируем для удобства
print(res4[0]) # первый вектор
print(res4[1]) # первый вектор

[-0.89442719  0.4472136 ]
[-0.70710678 -0.70710678]


## Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
matrix1 = np.array([[1,0], [0, 1]])
np.linalg.det(matrix1)

1.0