# Уровень 0

Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

In [ ]:
import numpy as np
import sympy as sym

In [ ]:
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию
film_2 = np.array([0,1,0,1,0,0])      # Ярость
film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства
film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

## Задание 1

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [ ]:
np.linalg.norm(film_2) # Евклидова норма

1.4142135623730951

In [ ]:
np.linalg.norm(film_3)

1.7320508075688772

In [ ]:
np.linalg.norm(film_2) * np.linalg.norm(film_3)

2.4494897427831783

In [ ]:
# Косинус угла между векторами

np.arccos(np.dot(film_2, film_3) / (np.linalg.norm(film_2) * np.linalg.norm(film_3)))

1.1502619915109316

In [ ]:
# Конвертация в градусы

np.rad2deg(np.arccos(np.dot(film_2, film_3) / (np.linalg.norm(film_2) * np.linalg.norm(film_3))))

65.90515744788931

# Уровень 1

## Задание 2

Вычислить с помощью Python значение первой производной для функции 8x(x+3)^2
 в точке x=1

In [ ]:
x = sym.Symbol('x')
res = sym.diff((8 * x * (x + 3) ** 2), x)
print(res)

8*x*(2*x + 6) + 8*(x + 3)**2


In [ ]:
res.subs(x, 1)

192

## Задание 3
Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу


In [ ]:
total_film = np.array([film_1, film_2, film_3, film_4])
print(total_film)

[[0 0 0 0 1 0]
 [0 1 0 1 0 0]
 [0 0 1 1 1 0]
 [1 0 0 1 0 1]]


In [ ]:
vector = np.array([1, 2, 3, 4])
res2 = np.dot(vector, total_film)
print(res2)

[4 2 3 9 4 4]
